export const KAL_ARATH_NAMES: string[] = [
  // Male names
  'Ahzar al-Saif', 'Ahzar ibn Malik', 'Akkad al-Rahl', 'Ammar ibn Dawud', 'Anwar al-Fadil',
  'Aqil al-Masur', 'Arash ibn Yusuf', 'Asad al-Badr', 'Askar ibn Tariq', 'Athar al-Karim',
  'Aziz ibn Rashid', 'Bahjat al-Saif', 'Bakr al-Nur', 'Bashir ibn Amir', 'Bazan al-Jabir',
  'Dawud al-Rashid', 'Dawud ibn Malik', 'Dhafir al-Qasim', 'Diya al-Din', 'Diyar ibn Khalid',
  'Faraj al-Nur', 'Farhan ibn Salim', 'Farouk al-Jabir', 'Faris ibn Omar', 'Fawzi al-Zafar',
  'Ghazi al-Murad', 'Ghalib ibn Tariq', 'Hakim al-Rashid', 'Hamid ibn Yusuf', 'Hasan al-Amir',
  'Hasim al-Nur', 'Haydar ibn Khalil', 'Hilal al-Saif', 'Husam ibn Rashid', 'Ibrahim al-Rashid',
  'Ihsan al-Qasim', 'Imad ibn Salim', 'Iskandar al-Zafar', 'Iyad ibn Yusuf', 'Jabir al-Karim',
  'Jalil al-Masur', 'Jamal ibn Rashid', 'Jawad al-Nur', 'Jazim ibn Tariq', 'Junayd al-Fadil',
  'Kamal al-Din', 'Kamil ibn Salim', 'Kareem al-Jabir', 'Khalid al-Zafar', 'Khalil ibn Omar',
  'Lutfi al-Qasim', 'Mahir ibn Yusuf', 'Malik al-Nur', 'Mansur ibn Tariq', 'Marwan al-Amir',
  'Masud ibn Rashid', 'Mazin al-Fadil', 'Mihail ibn Khalid', 'Mukhtar al-Saif', 'Munir ibn Salim',
  'Nabil al-Qasim', 'Nadir ibn Yusuf', 'Najib al-Rashid', 'Nasser ibn Tariq', 'Nawfal al-Karim',
  'Nizar al-Badr', 'Omar al-Hanif', 'Osman ibn Rashid', 'Qasim ibn Yusuf', 'Qays al-Masur',
  'Rafiq ibn Tariq', 'Rashid al-Fadil', 'Rayhan ibn Omar', 'Riyad al-Nur', 'Roshan ibn Khalid',
  'Sabir al-Qasim', 'Safwan ibn Yusuf', 'Saif al-Badr', 'Salah ibn Tariq', 'Salim al-Karim',
  'Saqr al-Zafar', 'Sarhang ibn Rashid', 'Shaheen al-Masur', 'Shakir ibn Salim', 'Sharif al-Nur',
  'Tahir al-Qasim', 'Tariq ibn Amir', 'Tawfiq ibn Yusuf', 'Thamer al-Fadil', 'Thamir ibn Khalid',
  'Uzun al-Badr', 'Walid ibn Tariq', 'Wasim al-Karim', 'Yazid al-Murad', 'Yusuf ibn Rashid',
  'Zafar al-Nur', 'Zahid ibn Salim', 'Zaid al-Masur', 'Zaki ibn Yusuf', 'Zayn al-Amir',
  // Female names
  'Ahlam al-Zahra', 'Aisha bint Tariq', 'Aliya al-Qamar', 'Amani bint Yusuf', 'Amira al-Nur',
  'Anisa bint Rashid', 'Arwa al-Layla', 'Asiya bint Khalid', 'Asma al-Salam', 'Aziza bint Omar',
  'Bahira bint Malik', 'Basima al-Qamar', 'Basira bint Salim', 'Batool al-Nur', 'Bushra bint Tariq',
  'Dalila al-Qamar', 'Dania bint Yusuf', 'Dima al-Ruh', 'Dina bint Rashid', 'Duha al-Sabah',
  'Fadila bint Khalid', 'Farha al-Zahra', 'Farida al-Nour', 'Fatin bint Omar', 'Fatoom al-Layla',
  'Ghada bint Tariq', 'Ghalia al-Qamar', 'Hadiya bint Yusuf', 'Hafsa al-Nour', 'Hana bint Rashid',
  'Haya al-Salam', 'Hind bint Khalid', 'Huda al-Nur', 'Husna bint Omar', 'Ibtihal al-Zahra',
  'Iman bint Tariq', 'Intisar al-Qamar', 'Iqbal bint Yusuf', 'Isra al-Layla', 'Izza bint Rashid',
  'Jamila bint Rashid', 'Jana al-Sabah', 'Jihan bint Khalid', 'Jumanah al-Nur', 'Karimah bint Omar',
  'Karima al-Layla', 'Kawkab bint Tariq', 'Khawla al-Zahra', 'Kholoud bint Yusuf', 'Laila al-Qamar',
  'Layla al-Sabah', 'Lina bint Rashid', 'Lubna al-Nur', 'Lujain bint Khalid', 'Madiha al-Salam',
  'Maisa bint Omar', 'Malika bint Yusuf', 'Maryam al-Zahra', 'Maysa bint Tariq', 'Mona al-Qamar',
  'Nadia bint Rashid', 'Nahed al-Nur', 'Nawal bint Khalid', 'Nihad al-Layla', 'Noor bint Omar',
  'Nour al-Sabah', 'Nasreen al-Ward', 'Qamar al-Dun', 'Rania al-Nur', 'Raniya bint Tariq',
  'Razan al-Zahra', 'Reem bint Yusuf', 'Rima al-Qamar', 'Ruba bint Rashid', 'Rula al-Salam',
  'Safiya bint Amir', 'Salma al-Ruh', 'Salwa bint Khalid', 'Samira al-Layla', 'Sana bint Omar',
  'Sara al-Nur', 'Shahad bint Tariq', 'Shaima al-Zahra', 'Siham bint Yusuf', 'Suhair al-Qamar',
  'Tahani bint Rashid', 'Tamara al-Sabah', 'Thanaa bint Khalid', 'Thuraya al-Nur', 'Wafa bint Omar',
  'Widad al-Layla', 'Wijdan bint Tariq', 'Wissam al-Zahra', 'Yasmin al-Badr', 'Yusra bint Yusuf',
  'Zahra bint Karim', 'Zainab al-Nur', 'Zayna bint Rashid', 'Zinah al-Qamar', 'Zuhour bint Tariq',
];
