export type OsricPublicationCategory = 'rules' | 'supplement' | 'adventure';

export interface OsricPublication {
  title: string;
  publishedYear: number;
  category: OsricPublicationCategory;
  description?: string;
  publisher?: string;
  levels?: string;
  purchased?: boolean;
  isTsr?: boolean;
}

export const OSRIC_PUBLICATIONS: OsricPublication[] = [

  // ── Core Rules ─────────────────────────────────────────────────────────────
  {
    title: 'OSRIC',
    publishedYear: 2013,
    category: 'rules',
    description: 'Hardcover second printing of the OSRIC retroclone (v2.2). Includes 11 new illustrations, expanded 4-page index, Index of Tables, and 70# interior paper. Originally released as a free PDF in 2006 by Stuart Marshall and Matthew Finch; v3.0 published 2025.',
    publisher: 'Black Blade Publishing & Usherwood Publications',
  },

  // ── Supplements ────────────────────────────────────────────────────────────
  {
    title: 'Monsters of Myth',
    publishedYear: 2011,
    category: 'supplement',
    description: 'Premier collection of more than 150 new monsters and creatures with over 75 illustrations by old-school artists. Released as a Free RPG Day product.',
    publisher: 'OSRIC Community',
  },
  {
    title: 'Malevolent and Benign',
    publishedYear: 2009,
    category: 'supplement',
    description: '128-page monster book featuring 150 creatures and more than 85 illustrations, with four appendices covering magic items, encounter levels, rarity, and terrain.',
    publisher: 'Expeditious Retreat Press',
  },
  {
    title: 'Monstrous Tome – Volume One',
    publishedYear: 2008,
    category: 'supplement',
    description: 'Monster supplement containing 32 new creatures — including Acid Vampires, Ethereal Stalkers, and Werebadgers — fully compatible with OSRIC.',
    publisher: 'Eldritch Enterprises',
  },
  {
    title: 'Monstrous Tome 2 – Book of Beings',
    publishedYear: 2010,
    category: 'supplement',
    description: 'More than one hundred new monsters including demons, dragons, and giants for use in First Edition-compatible games.',
    publisher: 'OSRIC Community',
  },
  {
    title: 'Mundane Magica',
    publishedYear: 2009,
    category: 'supplement',
    description: '36-page supplement exploring non-violent magic items alongside unconventional weapons and armor not found in the core rules.',
    publisher: 'OSRIC Community',
  },
  {
    title: 'Old-School Gazette #2',
    publishedYear: 2009,
    category: 'supplement',
    description: 'Five-page PDF supplement featuring new monsters, magic items, and spells for use with OSRIC and other First Edition-compatible games.',
    publisher: 'OSRIC Community',
  },
  {
    title: 'The Rogues Gallery',
    publishedYear: 1980,
    category: 'supplement',
    description: 'Hundreds of pre-rolled non-player characters of all classes and types, complete with alignments, personalities, and stats. An essential NPC reference for any 1e or OSRIC campaign.',
    publisher: 'TSR',
    isTsr: true,
  },

  // ── Adventures — OSRIC-Original ───────────────────────────────────────────

  // Levels 1
  {
    title: 'The Spider Farm',
    publishedYear: 2007,
    category: 'adventure',
    description: 'Mini-adventure designed for 1st-level characters.',
    publisher: 'OSRIC Community',
    levels: '1',
  },
  {
    title: 'F1: Zombie Curse',
    publishedYear: 2008,
    category: 'adventure',
    description: 'The small village of Crystal Shores is under a terrible curse — its inhabitants are growing sick and turning into zombies. An introductory adventure for first-level characters.',
    publisher: 'OSRIC Community',
    levels: '1',
  },
  {
    title: 'HM4 – Pop Goes the Meazel',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Four to six novice adventurers investigate a thief in the city of Rashtan in this first-level city-based mystery module.',
    publisher: 'OSRIC Community',
    levels: '1',
  },
  {
    title: 'Moganville',
    publishedYear: 2009,
    category: 'adventure',
    description: 'A village setting and adventure for first- and second-level characters in a logging community founded by Lord Gaennis Mogan, 70 miles southwest of Spaught in the world of Ulien.',
    publisher: 'Usherwood Publishing',
    levels: '1–2',
  },
  {
    title: 'TOWR1: Secret of the Sinister Sect',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Unexplained disappearances plague the village of Salt Bath. An investigation adventure for 1st- to 2nd-level characters.',
    publisher: 'OSRIC Community',
    levels: '1–2',
  },
  {
    title: 'Stele of the Silver Thane',
    publishedYear: 2008,
    category: 'adventure',
    description: 'An ambitious sorcerer schemes in fragmented eastern territories. Dungeon adventure for 1st- to 2nd-level characters.',
    publisher: 'Expeditious Retreat Press',
    levels: '1–2',
  },

  // Levels 1–3
  {
    title: 'The Shrine of Hecate',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Urban adventure featuring an abandoned tower and the notorious Axe Gang. Designed for 3–5 characters of 1st to 3rd level.',
    publisher: 'OSRIC Community',
    levels: '1–3',
  },

  // Levels 1–4
  {
    title: 'Stonepick Crossing',
    publishedYear: 2010,
    category: 'adventure',
    description: 'A town built atop an ancient dwarven dam harbors reports of disappearances and strange phenomena. Module for 6–10 adventurers of levels 1–3.',
    publisher: 'Brave Halfling Publishing',
    levels: '1–3',
  },
  {
    title: 'OB6: The Lost Mithral Mine',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Young dwarves follow a runestone map to reclaim a legendary mine. An all-dwarf adventure for 2nd-level characters.',
    publisher: 'OSRIC Community',
    levels: '2',
  },
  {
    title: 'The Pod-Caverns of the Sinister Shroom',
    publishedYear: 2007,
    category: 'adventure',
    description: 'Missing villagers and livestock lead to dark caverns beneath the limestone hills. One of the first major third-party OSRIC modules.',
    publisher: 'Expeditious Retreat Press',
    levels: '2–4',
  },
  {
    title: 'Shipwreck at Har\'s Point',
    publishedYear: 2009,
    category: 'adventure',
    description: 'A 1st Edition adventure for 4–6 characters involving a wrecked ship and the haunted spirits lingering near the shore.',
    publisher: 'OSRIC Community',
    levels: '2–4',
  },
  {
    title: 'The Witch Mounds',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Grass-covered barrows in Yoros Forest harbor ancient evil and mysterious greenish flames. Adventure for 3–6 characters.',
    publisher: 'OSRIC Community',
    levels: '3–6',
  },
  {
    title: 'The Frozen Wave Satsuma',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Frigid fog and mysterious seaborne raiders are attacking coastal settlements. 6–8 adventurers must investigate a foreign vessel. Levels 3–5.',
    publisher: 'OSRIC Community',
    levels: '3–5',
  },
  {
    title: 'The Secret of the Callair Hills',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Farm raids in a frontier region leave possessions untouched but inhabitants slain. Designed for 4–6 adventurers of levels 3–5.',
    publisher: 'OSRIC Community',
    levels: '3–5',
  },
  {
    title: 'The Lost Lair of Drecallis',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Adventurers investigate whether dragon Drecallis is truly dead or merely departed — and potentially claim an unguarded hoard. Levels 4–7.',
    publisher: 'OSRIC Community',
    levels: '4–7',
  },
  {
    title: 'Beneath Black Towen',
    publishedYear: 2010,
    category: 'adventure',
    description: 'Evil threatens the Land of Song and heroes must be found. Underground dungeon adventure for levels 4–6.',
    publisher: 'Brave Halfling Publishing',
    levels: '4–6',
  },
  {
    title: 'Dark Druids',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Evil druids in the Fang Forest have established outdoor areas and a three-level adventure site. Includes new magic items, monsters, and variant class descriptions.',
    publisher: 'OSRIC Community',
    levels: '4–6',
  },
  {
    title: 'Trident Rock',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Tournament adventure where players must unravel the mysteries of the island of Trident Rock. Levels 5–7.',
    publisher: 'OSRIC Community',
    levels: '5–7',
  },
  {
    title: 'Horror of Spider Point',
    publishedYear: 2008,
    category: 'adventure',
    description: 'Island-based adventure with a full adventure time plan, music guides, maps, and handouts. Compatible with Ravenloft-style horror.',
    publisher: 'OSRIC Community',
    levels: '5–7',
  },
  {
    title: 'The Red Mausoleum',
    publishedYear: 2009,
    category: 'adventure',
    description: '16 adventure-packed pages with detailed maps and descriptions. Set in the Sistermoors region, centered on an undead threat.',
    publisher: 'OSRIC Community',
    levels: '5–7',
  },
  {
    title: 'BQ1: The Patchwork Man',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Solve the riddles of the Patchwork Men and uncover their dark secret before the world succumbs to evil. Levels 6–9.',
    publisher: 'OSRIC Community',
    levels: '6–9',
  },
  {
    title: 'The Palace Beyond',
    publishedYear: 2010,
    category: 'adventure',
    description: 'An ancient, multidimensional palace with collapsing pocket dimensions and reality-crossing portals. Designed for 4–6 adventurers of levels 6–9.',
    publisher: 'OSRIC Community',
    levels: '6–9',
  },
  {
    title: 'The Doom of Red Rauthim',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Red Rauthim quests to slay the fire giant shaman Thjazi-Loki in revenge for a fallen companion. Levels 7–9.',
    publisher: 'OSRIC Community',
    levels: '7–9',
  },
  {
    title: 'Under Shattered Mountain',
    publishedYear: 2010,
    category: 'adventure',
    description: 'Soothsayers claim a devil lives beneath the dormant volcano. 5–8 adventurers explore tunnels under the mountain. Levels 9–12.',
    publisher: 'OSRIC Community',
    levels: '9–12',
  },
  {
    title: 'S8: Warren of the Withered Wyrm',
    publishedYear: 2010,
    category: 'adventure',
    description: 'Dragon-themed dungeon adventure with pre-generated characters included. Designed for levels 10–14.',
    publisher: 'Usherwood Publishing',
    levels: '10–14',
  },
  {
    title: 'Limbus Infernum',
    publishedYear: 2010,
    category: 'adventure',
    description: 'Characters begin dead in a demonic realm and must survive. Includes 17 scenarios and detailed survival rules for this unique planar setting.',
    publisher: 'OSRIC Community',
    levels: 'All',
  },
  {
    title: 'The Mad Demigod\'s Castle',
    publishedYear: 2010,
    category: 'adventure',
    description: 'Standalone dungeon level compatible with Castle of the Mad Archmage fan material.',
    publisher: 'OSRIC Community',
    levels: 'All',
  },
  {
    title: 'HU1: The Night Wolf Inn',
    publishedYear: 2009,
    category: 'adventure',
    description: 'Sandbox tavern setting featuring four floors, outdoor property, and extra-dimensional spaces filled with magical mysteries and intrigue.',
    publisher: 'HinterWelt Enterprises',
    levels: 'All',
  },

  // ── Adventures — Classic AD&D Compatible (TSR) ───────────────────────────
  {
    title: 'C2: The Ghost Tower of Inverness',
    publishedYear: 1979,
    category: 'adventure',
    description: 'Competition module from Wintercon VIII. Adventurers must retrieve the Soul Gem from an ancient keep in the Greyhawk setting.',
    publisher: 'TSR',
    levels: '5–7',
    isTsr: true,
  },
  {
    title: 'S2: White Plume Mountain',
    publishedYear: 1979,
    category: 'adventure',
    description: 'Notorious mountain reputed to be the haunt of demons and devils. Includes background, referee notes, player aids, and a cutaway view of the mountain complex. For 4–10 characters.',
    publisher: 'TSR',
    levels: '5–10',
    isTsr: true,
  },
  {
    title: 'Q1: Queen of the Demonweb Pits',
    publishedYear: 1980,
    category: 'adventure',
    description: 'Concluding module of the seven-part GDQ series. Adventurers confront Lolth, Queen of Demons, across planar maps and alternate worlds.',
    publisher: 'TSR',
    levels: '10–14',
    isTsr: true,
  },
  {
    title: 'A2: Secret of the Slavers Stockade',
    publishedYear: 1981,
    category: 'adventure',
    description: 'Part 2 of the four-module Slavers series. The battle against the slavers continues for characters of levels 4–7.',
    publisher: 'TSR',
    levels: '4–7',
    isTsr: true,
  },
  {
    title: 'I1: Dwellers of the Forbidden City',
    publishedYear: 1981,
    category: 'adventure',
    description: 'Jungle adventure involving a mysterious city of foul rituals. Adapted from the 1980 Origins convention tournament. Includes referee keys and eight maps.',
    publisher: 'TSR',
    levels: '4–7',
    isTsr: true,
  },
  {
    title: 'UK4: When a Star Falls',
    publishedYear: 1984,
    category: 'adventure',
    description: 'Prophecy and the Tower of the Heavens. Adventurers investigate sages whose uncanny predictions have drawn all manner of seekers.',
    publisher: 'TSR',
    levels: '3–5',
    isTsr: true,
  },
  {
    title: 'UK6: All That Glitters…',
    publishedYear: 1984,
    category: 'adventure',
    description: 'Jungle expedition following map fragments to locate treasure while navigating dangerous terrain and the murderous Atem. Levels 5–7.',
    publisher: 'TSR',
    levels: '5–7',
    isTsr: true,
  },
  {
    title: 'WG5: Mordenkainen\'s Fantastic Adventure',
    publishedYear: 1984,
    category: 'adventure',
    description: 'Mordenkainen and companions delve into Maure Castle to confront the Unopenable Doors and the potent evil beyond. High-level module.',
    publisher: 'TSR',
    levels: '9–12',
    isTsr: true,
  },
  {
    title: 'DL5: Dragons of Mystery',
    publishedYear: 1984,
    category: 'supplement',
    description: 'Dragonlance sourcebook providing background, maps, character sheets, and constellation guides necessary to run a complete Dragonlance campaign.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'N2: The Forest Oracle',
    publishedYear: 1984,
    category: 'adventure',
    description: 'The land lies under a curse. Adventurers must reach the Druids\' Oracle to potentially lift it and save the Downs. For levels 2–4.',
    publisher: 'TSR',
    levels: '2–4',
    isTsr: true,
  },
  {
    title: 'C3: The Lost Island of Castanamir',
    publishedYear: 1984,
    category: 'adventure',
    description: 'Island survival scenario with underground exploration. Adventure for characters of levels 1–4.',
    publisher: 'TSR',
    levels: '1–4',
    isTsr: true,
  },
  {
    title: 'OA2: Night of the Seven Swords',
    publishedYear: 1985,
    category: 'adventure',
    description: 'Political intrigue in Maeshi province: retrieve relics from Ito-jo Castle while avoiding a rival warlord\'s forces.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'UK7: Dark Clouds Gather',
    publishedYear: 1985,
    category: 'adventure',
    description: 'Powerful adventurers of levels 7–9 must confront a malevolent force threatening nearby mountain villages.',
    publisher: 'TSR',
    levels: '7–9',
    isTsr: true,
  },
  {
    title: 'I8: Ravager of Time',
    publishedYear: 1986,
    category: 'adventure',
    description: 'Adventure set in the Ffenargh bogs involving a murder mystery and an ancient evil awakening. For levels 8–10.',
    publisher: 'TSR',
    levels: '8–10',
    isTsr: true,
  },
  {
    title: 'I10: Ravenloft II – The House on Gryphon Hill',
    publishedYear: 1986,
    category: 'adventure',
    description: 'Sequel to Ravenloft. Adventurers return to Mordentshire and Count Von Zarovich\'s domain, navigating a realm where nightmare and reality blur.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'N4: Treasure Hunt',
    publishedYear: 1986,
    category: 'adventure',
    description: 'Characters begin at 0-level without a class, washed ashore on a barren island amid orc and goblin competition. Designed for beginning or experienced players seeking a unique challenge.',
    publisher: 'TSR',
    levels: '0',
    isTsr: true,
  },
  {
    title: 'DL12: Dragons of Faith',
    publishedYear: 1986,
    category: 'adventure',
    description: 'Dragonlance adventure set in the Blood Sea of Istar. Heroes seek ancient artifacts across levels 9–10. Includes TALIS cards and BATTLESYSTEM miniatures rules.',
    publisher: 'TSR',
    levels: '9–10',
    isTsr: true,
  },
  {
    title: 'I3-5: Desert of Desolation',
    publishedYear: 1987,
    category: 'adventure',
    description: 'Epic campaign trilogy set in the Raurin desert — spirit-guarded pyramids, crystalline obelisks, and gemstones with mysterious properties. Compilation of I3, I4, and I5.',
    publisher: 'TSR',
    levels: '4–10',
    isTsr: true,
  },
  {
    title: 'I12: Egg of the Phoenix',
    publishedYear: 1987,
    category: 'adventure',
    description: 'What begins as stopping a slavery ring escalates into retrieving lost artifacts across multiple planes and locations.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'I13: Adventure Pack I',
    publishedYear: 1987,
    category: 'adventure',
    description: 'Collection of 12 short stand-alone modules for DMs seeking variety without extensive preparation. Various character levels.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'N3: Destiny of Kings',
    publishedYear: 1987,
    category: 'adventure',
    description: 'Succession conflict threatens the kingdom of Dunador. Classic 1st Edition module involving court intrigue and combat.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'FRC1: Ruins of Adventure',
    publishedYear: 1987,
    category: 'adventure',
    description: 'Connected short adventures set in Phlan — a great evil descended on the town and adventurers must reclaim it. Shares the setting of the Pool of Radiance video game.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'FR1: Waterdeep and the North',
    publishedYear: 1987,
    category: 'supplement',
    description: 'Sourcebook for the city of Waterdeep and the surrounding Northern region, covering trade, intrigue, and the great hub of the Realms.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'FR3: Empires of the Sands',
    publishedYear: 1988,
    category: 'supplement',
    description: 'Campaign sourcebook detailing three lands of the Forgotten Realms: Amn, Tethyr, and Calimshan.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'FR4: The Magister',
    publishedYear: 1988,
    category: 'supplement',
    description: 'Compilation of spells and magical items for the Forgotten Realms, by Ed Greenwood and Steve Perrin.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'FR5: The Savage Frontier',
    publishedYear: 1988,
    category: 'supplement',
    description: 'Campaign sourcebook detailing the cultures, economies, cities, and wilderness of the Savage Frontier north of Waterdeep.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'WG8: Fate of Istus',
    publishedYear: 1989,
    category: 'adventure',
    description: 'Linked campaign adventures across Greyhawk where a dread plague tests each major character class. For levels 7–11.',
    publisher: 'TSR',
    levels: '7–11',
    isTsr: true,
  },
  {
    title: 'FRC2: Curse of the Azure Bonds',
    publishedYear: 1989,
    category: 'adventure',
    description: 'Adventurers discover mysterious blue tattoos and must uncover the conspiracy behind them. Based on the Azure Bonds novel by Jeff Grubb and Kate Novak.',
    publisher: 'TSR',
    isTsr: true,
  },
  {
    title: 'WG10: Child\'s Play',
    publishedYear: 1992,
    category: 'adventure',
    description: 'Adventure module designed to teach new DMs and players the AD&D system. Despite its introductory purpose, it contains challenges that can end a careless character\'s career abruptly.',
    publisher: 'TSR',
    isTsr: true,
  },
];
